name: smilarm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.3.0-279.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: ^3.0.4
  audioplayers: ^5.2.1
  camera: ^0.10.5+9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  google_ml_kit: ^0.16.3
  tflite_flutter: ^0.10.4
  go_router: ^13.2.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  collection: ^1.18.0
  intl: ^0.19.0
  uuid: ^4.3.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true