name: smilarm
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: ">=3.3.0-279.0.dev <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  android_alarm_manager_plus: ^3.0.4
  camera: ^0.10.5+9
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.4.10
  google_mlkit_face_detection: ^0.9.0
  go_router: ^13.2.0
  cupertino_icons: ^1.0.6
  shared_preferences: ^2.2.2
  gap: ^3.0.1
  collection: ^1.18.0
  intl: ^0.18.1
  flutter_local_notifications: ^16.3.2
  flutter_styled_toast: ^2.2.1
  disable_battery_optimization: ^1.1.1
  just_audio: ^0.9.36
  just_audio_background: ^0.0.1-beta.11

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  custom_lint: ^0.6.0
  riverpod_lint: ^2.3.9

flutter:
  uses-material-design: true
  assets:
    - assets/
